### ISSUE TITLE
"Start Simulator" button does nothing

### ISSUE THREAD

**Issue by tballmsft** [microsoft/devicescript#211]
I've got code compile and under watch, but "Start Simulator" button does nothing (even though it is enabled):

![image](https://user-images.githubusercontent.com/10767146/224788640-62c71799-e9de-4ee7-8c9d-1875e3b00270.png)

**Comment by pelikhan** [comment]
<img width="467" alt="image" src="https://user-images.githubusercontent.com/4175913/224887314-e252bd2c-0fd3-47a2-a6db-45d023598cbe.png">

**Comment by pelikhan** [comment]
@mmoskal it seems that we are trying to be too smart about dependenceis on @devicescript/compiler (parseAnyInt leaked into vscode).

**Comment by pelikhan** [comment]
fixed

**Comment by mmoskal** [comment]
we could just always embed `@devicescript/compiler` instead of loading it from node_modules

**Comment by pelikhan** [comment]
The solution was to use @devicescript/interop
