### ISSUE TITLE
breakpoints not working in sample

### ISSUE THREAD

**Issue by tballmsft** [microsoft/devicescript#219]
I've got the getting-started sample running but when I set a breakpoint (while the program is running or before I run the program ), it doesn't fire.  You can see the console.log is printing 'click!' but the breakpoint isn't firing

![image](https://user-images.githubusercontent.com/10767146/225137648-cebe712a-f814-4ffa-b4f4-cec0d9c051e0.png)

**Comment by pelikhan** [comment]
is this using the manually installed vsix?

**Comment by tballmsft** [comment]
yes

**Comment by pelikhan** [comment]
Fixed please test @tballmsft
