### ISSUE TITLE
"Reset device" drops connection

### ISSUE THREAD

**Issue by mmoskal** [microsoft/devicescript#245]
When I right click on ESP32-C3 device (I don't think this is device-specific) and select "reset device" it resets it, gets a bunch of logging input and then drops serial connection. Not sure why.

**Comment by pelikhan** [comment]
@mmoskal not sure what's happening, it seems that the device does not respond to serial after reset. could it be on the c++ side?

**Comment by pelikhan** [comment]
Also impacts debugging experience with simulator.
