### ISSUE TITLE
jacdac icon for terminal is not resolved in windows

### ISSUE THREAD

**Issue by pelikhan** [microsoft/devicescript#269]
windows only: 
![image](https://user-images.githubusercontent.com/4175913/227658986-c76cb624-9d75-47a5-863c-a58407d5e56c.png)

**Comment by mmoskal** [comment]
I've seen this on macOS too. I think this appears when there is no regular terminal and only DevS terminal

**Comment by mmoskal** [comment]
Just reproed on mac - just close the "bash" terminal window
