### ISSUE TITLE
can't load websocket-polyfill when building install cli

### ISSUE THREAD

**Issue by pelikhan** [microsoft/devicescript#27]
Do we need to run the program through the VM at build time?

**Comment by mmoskal** [comment]
The polyfill is only required if you want to run DS programs and they need to connect to the network. I guess if websocket polyfill doesn't require native compilation, then maybe we should just require it?

**Comment by pelikhan** [comment]
We should just require and add it as a dep of devicescript-vm. This error appears in all scripts.

**Comment by pelikhan** [comment]
Fixed by the no-deploy commit?

**Comment by mmoskal** [comment]
You mean it doesn't display the error? yes.
