### ISSUE TITLE
console.log of objects

### ISSUE THREAD

**Issue by pelikhan** [microsoft/devicescript#275]
A cool logging trick in js is to structure variables into an object before logging. This prints 'map'.

```
    const pid = await readWord()
    console.log({ pid })
```

**Comment by mmoskal** [comment]
Do we want `"" + { pid }` to return `"[Object]"` or `"{ pid: 12 }"`? (def. not current `"map"`)
I think the second option is better than special-casing `console.log()`.

**Comment by pelikhan** [comment]
Imo we should err towards matching v8 behavior , so (1)
________________________________

**Comment by pelikhan** [comment]
But console.log({pid}) should expand it

**Comment by mmoskal** [comment]
IMHO `.toString()` returning `"[Object]"` is one of the most useless "features" of JS. The only reason to support it would be  code like `if (x.toString()  == "[Object]")` in some legacy libraries, but we do not support legacy libraries anyways and such code is brittle beyond repair in V8 as well (eg. overriding `.toString()`).

**Comment by pelikhan** [comment]
yes, but that's what seasoned web dev expect. Also a large object could accidentally be converted to json, not sure that's wanted.

**Comment by mmoskal** [comment]
They expect it - so they won't even try to run `.toString()` on objects, so they won't be surprised.

It would have limits like `util.inspect()` in node.

Special-casing `console.log()` means ``` console.log(`foo: ${x}`) ``` is quite different from `console.log("foo:", x)`, and also you can't do `mylog("foo:" + x)`

**Comment by mmoskal** [comment]
It currently applies to `console.log()` and template strings but not to "+" unless used in `console.log()` - I guess we need to clean this up later
