### ISSUE TITLE
enabling title buttons

### ISSUE THREAD

**Issue by mmoskal** [microsoft/devicescript#283]
Instead of matching on `src/main*.ts` we could have the extension set the set of supported folders (that is folders that have `devsconfig.json` and their `src` subfolders) and use that in the `"when":` clauses

see https://code.visualstudio.com/api/references/when-clause-contexts#in-and-not-in-conditional-operators

**Comment by pelikhan** [comment]
added; do you still want the match on main.ts? I was thinking that hit debug/run on any file under that folder would find the debug entry point.

**Comment by mmoskal** [comment]
sounds good; can you pop up quick pick if more than one entry point?
