### ISSUE TITLE
Version of devicescript.vsix

### ISSUE THREAD

**Issue by louisvangeldrop** [microsoft/devicescript#285]
I download the latest version of devicescript.vsix -e.g. 2.2.5 today, install it using the extensions tab, I always end up with a previous version -2.2.4 in this example.

**Comment by pelikhan** [comment]
great catch

![image](https://user-images.githubusercontent.com/4175913/228040271-5b2d387c-69c3-4153-a847-e3a71a524397.png)

**Comment by pelikhan** [comment]
@mmoskal do you patch the package.json files before doing a build?

**Comment by pelikhan** [comment]
Fixed! Thankf or reporting.
