### ISSUE TITLE
realtimeclock error

### ISSUE THREAD

**Issue by louisvangeldrop** [microsoft/devicescript#300]
1. I am using a raspberry pi pico_w mcu flashed with the latest firmware
2. const realTimeClock = new ds.RealTimeClock()
3. await realTimeClock.setTime(2023, 3, 29, 1, 21, 20, 0)
4. The program blocks.

**Comment by pelikhan** [comment]
The program will block until it finds a server of RealTimeClock on the bus. Try to start the realtime clock server using the simulator page and it should keep going.

**Comment by pelikhan** [comment]
I've added a few more notes in the JSDocs about this behavior.

**Comment by pelikhan** [comment]
Keeping this issue open to track general "no sensor lock" issue.

**Comment by pelikhan** [comment]
tracked in https://github.com/microsoft/devicescript/issues/310
