### ISSUE TITLE
new icon

### ISSUE THREAD

**Issue by pelikhan** [microsoft/devicescript#31]
the dino is cool but...

**Comment by mmoskal** [comment]
final:
![MicrosoftTeams-image (9)](https://user-images.githubusercontent.com/10673976/205769267-d65d2d29-61ff-4ead-b6eb-20b36a523eb8.png)
wip:
![MicrosoftTeams-image (8)](https://user-images.githubusercontent.com/10673976/205769283-f4bd626c-88eb-46a9-b554-d57fdffb16c8.png)
![MicrosoftTeams-image (6)](https://user-images.githubusercontent.com/10673976/205769285-9171962b-1208-4089-885b-94d3d9486a3b.png)
![MicrosoftTeams-image (5)](https://user-images.githubusercontent.com/10673976/205769286-0948487f-982d-413a-baa7-2a6aa6b54769.png)

**Comment by mmoskal** [comment]
![dslogo](https://user-images.githubusercontent.com/10673976/205769547-6b7749d3-0d99-4553-95c1-ccf713bb1f25.svg)
[src.zip](https://github.com/microsoft/devicescript/files/10159045/src.zip)
