### ISSUE TITLE
rename dsboards to devicescript

### ISSUE THREAD

**Issue by pelikhan** [microsoft/devicescript#319]

**Comment by mmoskal** [comment]
we could rename it to `@devicescript-boards` or `@devs-boards`; I don't want to put all boards under `@devicescript/` because it will clutter intellisense when doing `import "@devicescript/_"`

**Comment by pelikhan** [comment]
but doing "@devicescript-boards" has more implications, it really means "new organization". I think we probably pollute the intellisense because typically symbols are added through intellisense.
