### ISSUE TITLE
consider having `delay` which common in JS/TS land to do a sleep

### ISSUE THREAD

**Issue by pelikhan** [microsoft/devicescript#320]
bluebird and in general many JS codebases use delay... which pushes cahtgpt to use it.

**Comment by mmoskal** [comment]
top-level `delay`, `Promise.delay` or `ds.delay` ?

**Comment by pelikhan** [comment]
```
import { delay } from "@devicescript/core"
```

**Comment by mmoskal** [comment]
feel free to add `ds_impl.delay = sleep` ;)
