### ISSUE TITLE
default role naming add 2 __

### ISSUE THREAD

**Issue by pelikhan** [microsoft/devicescript#389]
![image](https://github.com/microsoft/devicescript/assets/4175913/d417496e-dd05-4a0a-9ea2-a4ec482b1aa6)

Recomendation: no _, just the number.

**Comment by mmoskal** [comment]
there was no double `_` but removed the single `_`

**Comment by mmoskal** [comment]
oh, found the double `_` - the reason it was double was to avoid the conflict with the single generated in _allocRole; now that there is no underscore in _allocRole, I replaced the double with single
