### ISSUE TITLE
MQTT support

### ISSUE THREAD

**Issue by pelikhan** [microsoft/devicescript#395]
"Direct" Mqtt support, instead of wssk+gateway.

**Comment by amir-arad** [comment]
This was the first thing I looked for in the docs, after the list of supported boards.

**Comment by pelikhan** [comment]
Thanks, this is great feedback.

**Comment by pelikhan** [comment]
Fixed by https://github.com/microsoft/devicescript/pull/513, abvailable in v2.13.7
