### ISSUE TITLE
document memory/flash requirements

### ISSUE THREAD

**Issue by pelikhan** [microsoft/devicescript#397]
Probably in the device section and intro.

**Comment by aecorredor** [comment]
@pelikhan is Flash Encryption for ESP32 chips supported?: https://docs.espressif.com/projects/esp-idf/en/latest/esp32/security/flash-encryption.html#flash-encryption-efuse.

If not, I'm wondering if we'd be able to activate Flash Encryption with ESP-IDF directly, and then keep developing with DeviceScript. I'm just unsure about `idf.py encrypted-flash` being supported in DeviceScript. It seems like you have your own flashing tooling.

**Comment by pelikhan** [comment]
This one is for @mmoskal . For reference, the esp32 runtime is at https://github.com/microsoft/devicescript-esp32 and builds on top of ESP-IDF directly.

**Comment by mmoskal** [comment]
The flash encryption Should-Just-Work(TM). We store user program in NVM but I think this is handled transparently. Having said that I have not tried...
