### ISSUE TITLE
Add support for setStatusLight in pico-w

### ISSUE THREAD

**Issue by pelikhan** [microsoft/devicescript#404]
setStatusLight needs to talk to talk to the wireless chip to control the onboatd LED on the pico-w.

- knowledge of pico SDK will help
- fix at https://github.com/microsoft/devicescript-pico

**Comment by pelikhan** [comment]
The onboard LED does not seem to work on pico/pico-w

**Comment by lukeh990** [comment]
I'm trying to use setStatusLight on a regular Pico and I get a error reading `JDUSB Error: crc err`

Here is what the code I'm running in `main.ts`:
```ts
import { setStatusLight } from "@devicescript/runtime";

console.log(":)");
await setStatusLight(1);
```

**Comment by pelikhan** [comment]
Is this a fresh install? Could you try to flash the firmware again. We just did a release with sockets support.
________________________________

**Comment by pelikhan** [comment]
we might have been in the middle of upgrading the firware. could you try to upgrade the vscode extension and create a new project for the pico?

**Comment by pelikhan** [comment]
@mmoskal it seems that setStatusLight is not working on the pico itself.

**Comment by JackTam1993** [comment]
I met the same problem. the firmware and the vscode extension are the latest.

Raspberry Pi Pico W version: v2.10.900
