### ISSUE TITLE
Error in simulator after fresh setup

### ISSUE THREAD

**Issue by jurosh** [microsoft/devicescript#405]
After fresh install and new project creation, it's not possible to run Simulator.

Error:

```
DeviceScript - Install Node.JS dependencies to enable tools.
```
- Installation went OK, only one notice: ` YN0031: │ One or more node_modules have been detected and will be removed. This operation may take some time.`

Environment:

```
Linux
NodeJs v18.12.1
Yarn 3.3.0
```

**Comment by jurosh** [comment]
Looks like there is no support for Yarn (other than v1). It's probably needed to add `.yarnrc.yml` with `nodeLinker: node-modules` - that seems to fix it.

**Comment by pelikhan** [comment]
We are still using `yarn` v1, are you saying `.yarnrc.yml` should be added to the generated files? thanks for reporting!

**Comment by jurosh** [comment]
If I understand correctly how `init.ts` works, this might fix it...
https://github.com/microsoft/devicescript/pull/406

**Comment by pelikhan** [comment]
In 2.9.13. Thanks!
