### ISSUE TITLE
@devicescript/gpio does not export some functions

### ISSUE THREAD

**Issue by wh1tecat-nya** [microsoft/devicescript#409]
in [servers/pins document](https://microsoft.github.io/devicescript/developer/servers/pins#pinmode),
`pinMode, digitalWrite, digitalRead, subscribeDigital` are exported by `@devicescript/gpio`

![image](https://github.com/microsoft/devicescript/assets/6924358/a11c9b8b-f4d7-4961-89c5-52d5f18721bb)
(sorry error message is Japanese, but [TS2305](https://typescript.tv/errors/#TS2305) is `no exported member` error.)

but in my workspace, it doesn't.
which is correct?

**Comment by pelikhan** [comment]
Could you make sure the reference to devicescript dependencies in package.json are >= 2.9.13 ?

**Comment by wh1tecat-nya** [comment]
Sorry for the slow response.
I had v2.9.12 and update it, I got it resolved. 
Thank you!
