### ISSUE TITLE
Implement es Set class

### ISSUE THREAD

**Issue by pelikhan** [microsoft/devicescript#496]
Support for https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set

Guide: https://microsoft.github.io/devicescript/contributing#add-core-javascript-apis

**Comment by KevinL10** [comment]
Hi @pelikhan! I'm interested in working on this – could you assign me to the issue?

**Comment by pelikhan** [comment]
Great! @mmoskal any guidance around implementing set? Does this require special handling from the C runtime?

**Comment by mmoskal** [comment]
I think for now just use Array.includes. We are unlikely to add anything faster anytime soon
