### ISSUE TITLE
Implement es Map class 

### ISSUE THREAD

**Issue by pelikhan** [microsoft/devicescript#497]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map

Guide: https://microsoft.github.io/devicescript/contributing#add-core-javascript-apis

**Comment by Bohemus307** [comment]
I have an interest in taking this on.

**Comment by pelikhan** [comment]
You are on!

**Comment by Bohemus307** [comment]
PR opened https://github.com/microsoft/devicescript/pull/538
