### ISSUE TITLE
Regardless of whether I use npm upgrade @devicescript/cli or npm i @devicescript/cli, the version of @devicescript/cli remains 2.13.5.

### ISSUE THREAD

**Issue by Chaos-Enyo** [microsoft/devicescript#512]
**Describe the bug**
Regardless of whether I use npm upgrade @devicescript/cli or npm i @devicescript/cli, the version of @devicescript/cli remains 2.13.5.
**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by pelikhan** [comment]
Is the @devicescript/cli version pinned in package.json?
