### ISSUE TITLE
mcuTemperature block

### ISSUE THREAD

**Issue by louisvangeldrop** [microsoft/devicescript#514]
The following code blocks at a Seeed Studio Xiao ESP32C3:

import { Control } from "@devicescript/core"

const control = new Control()
// ...
const value = await control.mcuTemperature.read()

**Comment by pelikhan** [comment]
Arg, Control is one of those services you should not instantiate yourself. Check out this doc https://microsoft.github.io/devicescript/developer/mcu-temperature/

**Comment by louisvangeldrop** [comment]
Thx.  It works now. I searched for mcuTemperature and found the sample using the control object.

**Comment by pelikhan** [comment]
Ha I need to fix the docs on Control...

**Comment by pelikhan** [comment]
fix https://github.com/microsoft/devicescript/commit/cba6d1f0e60d9472be334420bb71d5763566e306
