### ISSUE TITLE
Can not connect to device

### ISSUE THREAD

**Issue by louisvangeldrop** [microsoft/devicescript#570]
Start the DeviceScript Extension version 2.14.3 => Connect Device => results in the messages:

1. DeviceScript - Unable to locate Node.JS v16+.
2. The terminal process failed to launch: Path to shell executable "C:\Program Files\nodejs" is not a file or a symlink.

**Comment by louisvangeldrop** [comment]
As a solution I have added: "node": "^18.0.0" to package.json

**Comment by louisvangeldrop** [comment]
Fixed by running "npm update"

**Comment by pelikhan** [comment]
I've beefed up the help with this error message. https://github.com/microsoft/devicescript/commit/941084f4ad58e701bbad6dfdf4a166eff6d66a60
