### ISSUE TITLE
"Create new project" doesn't work in empty folder

### ISSUE THREAD

**Issue by mmoskal** [microsoft/devicescript#572]
repro: create an empty folder, start VSCode there, select "DeviceScript: Create new project..."

it asks to select board but doesn't give any choices (other than Help me choose) probably because the devtools are not running

**Comment by pelikhan** [comment]
Fixed by https://github.com/microsoft/devicescript/commit/4fd960d0120f2f0d44e8bb79f28fd79afe8322d1
