### ISSUE TITLE
fix remaining js sample

### ISSUE THREAD

**Issue by pelikhan** [microsoft/devicescript#6]
The "old" docs still have various samples that don't fully compile. search for 

    ```js

**Comment by mmoskal** [comment]
Changing the only remaining sample from js to ts doesn't break the build.

However, it doesn't look like the `language.config.js` is ever used - in `docusaurus.config.js` the constant `languageConfig` is never used. I also couldn't find `processToExecute` anywhere in `node_modules/*`; also `compile.js` doesn't return an error code

**Comment by pelikhan** [comment]
All errored samples are now marked with `ignore-errors` and will fail the build if this flag is removed.

**Comment by mmoskal** [comment]
can't find any `ignore-errors`, please reopen if needed
