### ISSUE TITLE
Add ESP32-C3FH4-RGB

### ISSUE THREAD

**Issue by gsteiert** [microsoft/devicescript#612]
Add support for ESP32-C3FH4-RGB 
https://github.com/01Space/ESP32-C3FH4-RGB

The attached file should take care of it if you remove the .txt suffix

**Additional context**
[esp32_c3fh4_rgb.board.json.txt](https://github.com/microsoft/devicescript/files/12424967/esp32_c3fh4_rgb.board.json.txt)

**Comment by pelikhan** [comment]
@mmoskal let's chat about bringing this in.

**Comment by gsteiert** [comment]
Any status on this?  Do you need help with the board page?

**Comment by pelikhan** [comment]
It slipped through the cracs. We'll take a look soon.

**Comment by pelikhan** [comment]
Could you take a picture of this device using this template and attach it to the bug? 

https://microsoft.github.io/jacdac-docs/templates/jacdac-device-photo-template.pdf

**Comment by gsteiert** [comment]
Will this work?
![IMG_20230911_195519](https://github.com/microsoft/devicescript/assets/41132966/13b9398e-b293-4cce-95f0-e6a4fb355f8c)

**Comment by gsteiert** [comment]
this might be a little better
![IMG_20230911_200206](https://github.com/microsoft/devicescript/assets/41132966/cae636ff-ec59-4615-9fbf-07f958ccf509)

**Comment by pelikhan** [comment]
https://github.com/microsoft/jacdac/pull/1329

**Comment by mmoskal** [comment]
should be fixed now (once everything builds)

**Comment by gsteiert** [comment]
Thanks for adding the board.
It might be nice to mention the 5x5 LED grid is connected to LEDS pin GPIO8 on the board page.
This makes a good board to demo the LED driver.

![IMG_20230911_194228](https://github.com/microsoft/devicescript/assets/41132966/d3344675-0ebd-4098-a9e4-51c91548a169)

**Comment by pelikhan** [comment]
Right we need to support having a bit of typescript in the board definition.

**Comment by pelikhan** [comment]
example added https://github.com/microsoft/devicescript/commit/ca5fa26485df3addbb2d7225ecb8f08dccfb9135
