### ISSUE TITLE
Support for hall effect sensor SS49E 

### ISSUE THREAD

**Issue by APantelides** [microsoft/devicescript#620]
** Device description **

Hall effect sensor SS49E 

** Datasheet, firmware, etc... **

[Links to datasheet information](https://www.mouser.com/ProductDetail/Honeywell/SS49E?qs=%2Ffq2y7sSKcJBD3o5K2Vcgg%3D%3D)

**Comment by pelikhan** [comment]
Take a look at https://github.com/microsoft/devicescript/commit/9dab175dd10b712b5836d60c69085caa327455b2

**Comment by pelikhan** [comment]
see https://microsoft.github.io/devicescript/api/drivers/hall

**Comment by APantelides** [comment]
Very nice, thank you!
