### ISSUE TITLE
board schema refuses LED pin

### ISSUE THREAD

**Issue by pelikhan** [microsoft/devicescript#626]
Schema is too restrictive? 

![image](https://github.com/microsoft/devicescript/assets/4175913/6686ad76-5b2b-47c1-a85c-22b8f4295b9e)

https://github.com/microsoft/devicescript-esp32/blob/main/boards/esp32c3/esp32_c3fh4_rgb.board.json#L33

**Comment by mmoskal** [comment]
Didn't figure out how to allow extra properties. We could just not list any options here (and lose any intellisense)

**Comment by pelikhan** [comment]
can we add "LEDS" to the mix? it's a common sceneraio.
