### ISSUE TITLE
rename devsdbg to devicescriptdebugger

### ISSUE THREAD

**Issue by pelikhan** [microsoft/devicescript#81]
we use full "devicescript" in other service names

<img width="301" alt="image" src="https://user-images.githubusercontent.com/4175913/215681462-1ddcaab2-d93b-442f-9104-61165fd360df.png">

**Comment by pelikhan** [comment]
Right…. But abbreviation are harder to understand. Maybe another flag to control C constant generation?
________________________________

**Comment by mmoskal** [comment]
Then don't use abbreviations in the tree - just use the full service name. The lengthy constants also applies to TS...
